create edit form
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #105
Opened 2021-01-07 11:02 UTC by arnaudpilato

2021-01-07 11:09 UTC, BenjaminDbse submitted a review, later dismissed

2021-01-07 13:20 UTC, sblondeau requested changes
ta PR ne modifie pas la BDD, donc tu ne devrais pas avoir de migration
il faut bien que tu fasse un d:m:m dès que tu tires dev, puis que tu fasses un make:migration uniquement si tu modifie une entité

2021-01-11 07:39 UTC, BenjaminDbse submitted a review, later dismissed

2021-01-11 08:31 UTC, sblondeau requested changes
tu ne dois pas push des images "uploadée"
le contenu du dossier uploads ne doit pas etre versionné !
si c'est pour faire une "fixtures" pour le moment n'affiche pas d'image, le alt s'affichera
on vera mardi en LC comment gérer ça plus proprement

2021-01-11 10:11 UTC, BenjaminDbse submitted a review, later dismissed

2021-01-12 08:45 UTC, sblondeau requested changes

2021-01-12 08:45 UTC, sblondeau commented on templates/walking/admin.html.twig
> +                        <img src="{{ walking.picture }}{# {{ asset('uploads/' ~ walking.picture) }} #}">
hum ton image uploadée est bien dans le dossier uploads? donc il faut garder le  {{ asset('uploads/' ~ walking.picture) }}

2021-01-12 08:45 UTC, sblondeau commented on templates/walking/index.html.twig
>                      </div>
idem

2021-01-12 08:45 UTC, sblondeau commented on templates/walking/show.html.twig
> +                            <img src="{{ asset( walk.picture ) }}{# {{ asset('uploads/' ~ walk.picture) }} #}">
là c'est encore différent, tu as asset mais plus 'uploads'

2021-01-12 08:45 UTC, sblondeau commented on templates/walking/show.html.twig
> +                            <img src="{{ asset( walk.picture ) }}{# {{ asset('uploads/' ~ walk.picture) }} #}">
quand tu upload, on est d'accord que tu mets ton image dans public/uploads/ mais qu'en bdd tu ne stock que le nom du fichier (et pas tout le chemin). Donc il faut bien réécrire 'uploads' ici

2021-01-12 14:41 UTC, ChenuetLoic submitted a review, later dismissed

2021-01-12 15:46 UTC, sblondeau approved these changes

2021-01-12 15:46 UTC, merged