Fix admin home link
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #109
Opened 2021-01-07 13:43 UTC by ChenuetLoic

2021-01-07 13:47 UTC, AliNedjar submitted a review, later dismissed

2021-01-07 16:29 UTC, sblondeau requested changes

2021-01-07 16:29 UTC, sblondeau commented on migrations/Version20210107085202.php
> +final class Version20210107085202 extends AbstractMigration
encore une fois, tu m'as fais un make:migration alors que c'est pas nécessaire
c'est un d:m:m pour appliquer la migration que tu dois faire, quand tu tires dev, mais tu n'as pas à faire un make:mig si tu ne changes pas la structure de ta bdd.
donc fichier à enlever

2021-01-08 08:51 UTC, sblondeau approved these changes

2021-01-08 08:51 UTC, merged