changement demande client couleur et photo
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #134
Opened 2021-01-11 10:45 UTC by ChenuetLoic

2021-01-11 14:48 UTC, BenjaminDbse approved these changes, later dismissed

2021-01-12 09:01 UTC, sblondeau requested changes
ce sont bien des images non administrables ? 
donne leur des noms compréhensible ! (par ex coach_image.png, seance.png, etc) ça sera BEAUCOUP plus simple de t'y retrouver que "IMG_4510-compressed.jpg " ;-)

2021-01-12 12:46 UTC, AliNedjar approved these changes

2021-01-12 14:13 UTC, sblondeau approved these changes

2021-01-12 14:13 UTC, merged