creation de la page media
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #158
Opened 2021-01-12 14:14 UTC by ChenuetLoic

2021-01-12 15:04 UTC, AliNedjar submitted a review, later dismissed

2021-01-12 15:49 UTC, sblondeau requested changes

2021-01-12 15:49 UTC, sblondeau commented on templates/media/index.html.twig
> +                <h2>titre de la vidéo en bdd</h2>
?? ça doit venir d'une BDD non si j'ai bien compris ? donc il me faut une requete pour recup de la base, mettre l'id youtube de la base, faire des fixtures, etc

2021-01-12 16:17 UTC, AliNedjar submitted a review, later dismissed

2021-01-18 09:48 UTC, Sandra-Louchart approved these changes

2021-01-18 09:55 UTC, arnaudpilato approved these changes

2021-01-18 10:47 UTC, sblondeau approved these changes

2021-01-18 10:47 UTC, merged