Mise a jour entity opinion
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #175
Opened 2021-01-18 15:42 UTC by ChenuetLoic

2021-01-18 16:27 UTC, BenjaminDbse submitted a review, later dismissed

2021-01-18 16:34 UTC, sblondeau requested changes

2021-01-18 16:34 UTC, sblondeau commented on src/Controller/FitnessController.php
> +        $opinions = $opinionRepository->findBy(['page' => 'walking']);
fitness plutot que walking ? 
si tu dois récup ce type de données en fonction d'un string (fitness, walking, etc.) créé une constante par ex const FITNESS_PAGE = "fitness' et const WALKING_PAGE = 'walking'; ça sera beaucoup plus propre

2021-01-18 16:34 UTC, sblondeau commented on src/Form/OpinionType.php
> +                    'Remise en forme' => 'fitness',
et ici tu récupère tes constantes.
une autre solution c'est de créer une seule constantes PAGES qui serait un tableau (à toi de voir).

2021-01-18 16:34 UTC, sblondeau commented on src/Form/OpinionType.php
> +                    'Sport adapter' => 'adapted-activity',
"Sport adapté" plutot ?

2021-01-18 17:01 UTC, AliNedjar approved these changes, later dismissed

2021-01-18 17:31 UTC, sblondeau requested changes

2021-01-18 17:31 UTC, sblondeau commented on src/Form/OpinionType.php
> +                    'Remise en forme' => 'fitness',
il faut que tu gères cette partie aussi. Fais des constantes

2021-01-19 08:14 UTC, AliNedjar approved these changes, later dismissed

2021-01-19 10:18 UTC, sblondeau commented
tjs pas les constantes comme je voudrais, cherchez ensemble peut-etre ? et on en reparle après

2021-01-19 15:12 UTC, AliNedjar submitted a review, later dismissed

2021-01-19 15:37 UTC, sblondeau requested changes
constante à revoir

2021-01-19 15:45 UTC, AliNedjar submitted a review, later dismissed

2021-01-20 08:04 UTC, sblondeau approved these changes

2021-01-20 08:09 UTC, merged