create customer cards with crud
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #182
Opened 2021-01-19 14:18 UTC by arnaudpilato

2021-01-19 14:52 UTC, Sandra-Louchart approved these changes, later dismissed

2021-01-19 15:03 UTC, ChenuetLoic approved these changes, later dismissed

2021-01-19 15:24 UTC, sblondeau requested changes
je n'arrive pas à comprendre ta US, c'est un ajout ? un edit ? une suppression ? les US sont mal rédigées dans l'onglet projet

2021-01-19 15:24 UTC, sblondeau commented on src/Entity/User.php
> +    private ?string $lastname;
manque tous les Assert

2021-01-19 16:35 UTC, BenjaminDbse approved these changes

2021-01-20 08:11 UTC, sblondeau approved these changes

2021-01-20 08:11 UTC, merged