Us58 new activity
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #183
Opened 2021-01-19 14:43 UTC by Sandra-Louchart

2021-01-19 15:46 UTC, ChenuetLoic approved these changes, later dismissed

2021-01-19 15:48 UTC, AliNedjar submitted a review, later dismissed

2021-01-20 08:12 UTC, sblondeau requested changes

2021-01-20 08:12 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            $entityManager->flush();
manque un message flash

2021-01-20 10:15 UTC, AliNedjar approved these changes, later dismissed

2021-01-20 11:32 UTC, sblondeau submitted a review, later dismissed

2021-01-20 12:37 UTC, closed without merging