Us7 page modification admin media
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #190
Opened 2021-01-19 16:13 UTC by ChenuetLoic

2021-01-19 16:35 UTC, arnaudpilato approved these changes, later dismissed

2021-01-20 08:14 UTC, sblondeau requested changes

2021-01-20 08:14 UTC, sblondeau commented on src/Controller/AdminMediaController.php
> +            $this->addFlash('success', 'La vidéo à bien été modifié');
modifiée

2021-01-20 08:14 UTC, sblondeau commented on templates/admin/media/edit.html.twig
> +        <h1 class="text-center my-4">Modification des vidéo</h1>
vidéos

2021-01-20 10:13 UTC, AliNedjar approved these changes

2021-01-20 11:33 UTC, sblondeau approved these changes

2021-01-20 11:33 UTC, merged