Us8 supp page admin media
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #191
Opened 2021-01-19 16:17 UTC by ChenuetLoic

2021-01-19 16:37 UTC, arnaudpilato approved these changes, later dismissed

2021-01-20 08:15 UTC, sblondeau requested changes

2021-01-20 08:15 UTC, sblondeau commented on src/Controller/AdminMediaController.php
> +            $this->addFlash('danger', 'La vidéo à bien été supprimé');
supprimée

2021-01-20 10:13 UTC, AliNedjar approved these changes

2021-01-20 11:33 UTC, sblondeau approved these changes

2021-01-20 11:33 UTC, merged