finished new text part gym
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #211
Opened 2021-01-20 13:58 UTC by AliNedjar

2021-01-20 14:31 UTC, arnaudpilato approved these changes, later dismissed

2021-01-20 16:32 UTC, sblondeau requested changes

2021-01-20 16:32 UTC, sblondeau commented on src/Controller/GymController.php
> + * @Route("/salle_entrainement")
pas d'underscore dans des noms de route, plutot salle-entrainement

2021-01-20 16:32 UTC, sblondeau commented on src/Controller/GymController.php
> + * @Route("/salle_entrainement")
puis en fait là si tu préfixes par ça, tu va avoir des routes mal formées du style
salle-entrainement/admin/new ?? faut pas plutot prefixer par admin/salle-entrainement ? 
je te laisse check et corriger partout ou c'est nécessaire

2021-01-21 08:37 UTC, ChenuetLoic approved these changes, later dismissed

2021-01-21 08:40 UTC, sblondeau requested changes

2021-01-21 08:40 UTC, sblondeau commented on src/Controller/GymController.php
> + * @Route("/salle_entrainement")
tjs un underscore là

2021-01-21 09:08 UTC, ChenuetLoic approved these changes

2021-01-21 09:42 UTC, sblondeau approved these changes

2021-01-21 09:42 UTC, merged