Us18 creation compte client
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #216
Opened 2021-01-20 15:21 UTC by ChenuetLoic

2021-01-20 15:54 UTC, AliNedjar approved these changes, later dismissed

2021-01-21 08:08 UTC, sblondeau requested changes

2021-01-21 08:08 UTC, sblondeau commented on src/Entity/User.php
>  use phpDocumentor\Reflection\DocBlock\Tags\Return_;
c'est quoi ce use ?

2021-01-21 08:08 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +        $this->addFlash('success', 'Your email address has been verified.');
trad

2021-01-21 08:28 UTC, AliNedjar approved these changes

2021-01-21 08:37 UTC, sblondeau approved these changes

2021-01-21 08:37 UTC, merged