Us81 mise en place entity contact
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #261
Opened 2021-01-22 16:18 UTC by ChenuetLoic

2021-01-22 19:50 UTC, AliNedjar submitted a review, later dismissed

2021-01-25 08:37 UTC, sblondeau requested changes

2021-01-25 08:37 UTC, sblondeau commented on src/Entity/Contact.php
> +     *  @Assert\Length(max="255")
Assert\Email à ajouter

2021-01-25 10:51 UTC, sblondeau approved these changes

2021-01-25 10:51 UTC, merged