ajoute d'une table
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #282
Opened 2021-01-25 15:49 UTC by ChenuetLoic

2021-01-25 15:54 UTC, BenjaminDbse approved these changes

2021-01-25 15:55 UTC, BenjaminDbse approved these changes, later dismissed

2021-01-25 21:24 UTC, sblondeau requested changes

2021-01-25 21:24 UTC, sblondeau commented on src/DataFixtures/TariffFixtures.php
> +            $tarif->setDescription("Pour plus d'informations sur les tarifs n'hésiter pas à m'envoyer un email.");
n'hésitez

2021-01-25 21:24 UTC, sblondeau commented on src/Entity/Tariff.php
> +     */
manque Assert

2021-01-26 08:14 UTC, BenjaminDbse approved these changes, later dismissed

2021-01-26 09:22 UTC, sblondeau requested changes

2021-01-26 09:22 UTC, sblondeau commented on src/Entity/Tariff.php
> +     */
+ Assert\Length

2021-01-26 10:04 UTC, BenjaminDbse approved these changes

2021-01-26 11:33 UTC, sblondeau approved these changes

2021-01-26 11:33 UTC, merged