barnav
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #29
Opened 2020-12-09 10:43 UTC by ChenuetLoic

2020-12-09 10:48 UTC, BenjaminDbse submitted a review, later dismissed

2020-12-09 10:49 UTC, AliNedjar approved these changes, later dismissed
ça m'a l'air ok

2020-12-09 14:33 UTC, sblondeau requested changes
C'est quoi le 1er fichier "DG-Damien-Gouveia blanc.jpg " qui de plus a une espace dans son nom ? 
reprend les noms des images pour etre sur qu'il n'y a pas de doublons et avoir des noms comprehensibles
et attention certaines images sont trop volumineuses (pas plus de 200ko pour les grandes images et pas plus de 100ko pour des petites images)

2020-12-09 14:33 UTC, sblondeau commented on assets/styles/app.scss
> +    position: fixed;
pour fixer une navbar tu as une classe bootstrap, pas besoin de CSS

2020-12-09 15:26 UTC, arnaudpilato approved these changes, later dismissed

2020-12-09 15:50 UTC, sblondeau requested changes

2020-12-09 15:50 UTC, sblondeau commented on templates/include/_navbar.html.twig
> +    <nav class="navbar navbar-expand-lg navbar-dark bg-info position-fixed">
alors ça marche peut-etre mais c'est pas comme ça qu'il faut faire normalement, je te laisse reprendre la doc de bootstrap pour les navbar, la classe est "fixed-top" et non "position-fixed" ;-)

2020-12-09 16:26 UTC, arnaudpilato approved these changes

2020-12-10 09:03 UTC, Sandra-Louchart approved these changes

2020-12-10 10:43 UTC, sblondeau approved these changes

2020-12-10 10:43 UTC, merged