Fix flash message
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #371
Opened 2021-01-27 16:00 UTC by arnaudpilato

2021-01-27 17:01 UTC, ChenuetLoic submitted a review, later dismissed

2021-01-28 10:18 UTC, sblondeau requested changes

2021-01-28 10:18 UTC, sblondeau commented on templates/include/_footer.html.twig
> +        </div>git
un git qui traine !

2021-01-28 10:21 UTC, ChenuetLoic submitted a review, later dismissed

2021-01-28 10:36 UTC, merged