S01 us15 create nordic walking page
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #42
Opened 2020-12-11 13:43 UTC by arnaudpilato

2020-12-11 14:41 UTC, ChenuetLoic submitted a review, later dismissed

2020-12-12 23:02 UTC, sblondeau requested changes

2020-12-12 23:02 UTC, sblondeau commented on assets/styles/walking.scss
> +    background-color: rgba(0, 0, 0, 0.5);
couleur = variable scss

2020-12-12 23:02 UTC, sblondeau commented on templates/walking/show.html.twig
> +                        <div class="col-12 col-lg-5">
le col-12 est inutile car appliqué par défaut

2020-12-12 23:02 UTC, sblondeau commented on templates/walking/show.html.twig
> +                        <p class="col-12 col-lg-5">{{ walk.description }}</p>
idem

2020-12-12 23:02 UTC, sblondeau commented on templates/walking/show.html.twig
> +            <h1>Qu'est ce que la marche nordique ?</h1>
Qu'est-ce que (manque un tiret)

2020-12-14 15:22 UTC, ChenuetLoic submitted a review, later dismissed

2020-12-15 08:28 UTC, sblondeau approved these changes

2020-12-15 08:28 UTC, merged