changement titre et texte plus ajout photo
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #55
Opened 2020-12-11 15:16 UTC by ChenuetLoic

2020-12-11 15:20 UTC, arnaudpilato approved these changes, later dismissed

2020-12-12 23:05 UTC, sblondeau requested changes

2020-12-12 23:05 UTC, sblondeau commented on templates/home/index.html.twig
> +            <div class="container-fluid col-12">
col-12 est inutile, d'autant plus sur un container-fluid, ce n'est pas sa place

2020-12-12 23:05 UTC, sblondeau commented on templates/home/index.html.twig
> +                <div class="row d-flex justify-content-center ">
la classe row est en display:flex de base, donc le d-flex est inutile

2020-12-12 23:05 UTC, sblondeau commented on templates/home/index.html.twig
>          <div class="container-fluid bg-info text-light col-12 py-4">
col-12 à retirer

2020-12-15 08:10 UTC, AliNedjar approved these changes
ça m'a l'air bon

2020-12-15 08:29 UTC, sblondeau approved these changes

2020-12-15 08:29 UTC, merged