S01 us01 remise en forme fix
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #56
Opened 2020-12-11 15:20 UTC by AliNedjar

2020-12-11 15:21 UTC, arnaudpilato approved these changes, later dismissed

2020-12-12 23:09 UTC, sblondeau requested changes

2020-12-12 23:09 UTC, sblondeau commented on assets/styles/fitness.scss
>      background-color: rgba(0, 0, 0, 0.5);
couleur en variable

2020-12-14 15:23 UTC, ChenuetLoic approved these changes

2020-12-15 08:31 UTC, sblondeau approved these changes

2020-12-15 16:01 UTC, arnaudpilato approved these changes

2020-12-15 16:03 UTC, sblondeau approved these changes

2020-12-15 16:04 UTC, merged