Changement favicom
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #57
Opened 2020-12-11 15:23 UTC by ChenuetLoic

2020-12-11 15:28 UTC, arnaudpilato approved these changes, later dismissed

2020-12-12 23:08 UTC, sblondeau requested changes
non pour le coup il faut vraiment redimensionner l'image en 20x20 pour la favicon, pas seulement réduire le poids, car elle a jamais pour but d'etre affichée plus grand

2020-12-15 08:08 UTC, AliNedjar approved these changes, later dismissed
ça m'a l'air tout bon

2020-12-15 08:31 UTC, sblondeau approved these changes, later dismissed

2020-12-15 15:58 UTC, arnaudpilato approved these changes

2020-12-15 16:09 UTC, merged