Us29 page contact
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #67
Opened 2020-12-16 13:03 UTC by BenjaminDbse

2020-12-16 14:57 UTC, ChenuetLoic submitted a review, later dismissed

2020-12-17 08:25 UTC, sblondeau requested changes

2020-12-17 08:25 UTC, sblondeau commented on templates/contact/contact.html.twig
> +            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 pb-1">
col-xs-12 n'existe pas, c'est col-12 pour les petites tailles
mais col-12 c'est inutile de le spécifier car appliqué par défaut

2020-12-17 08:25 UTC, sblondeau commented on templates/contact/contact.html.twig
> +                        <tr>
tu veux faire quoi exactemetn là ? afficher uniquement l'horaire du jour ?
c'est pas mal le coup de la boucle mais c'est un peu compliqué ce que tu fais je pense, explique moi bien ce que tu veux en résultat pour qu'on optimise si besoin

2020-12-17 08:25 UTC, sblondeau commented on templates/contact/contact.html.twig
> +    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
bon si ça marche je vais pas te faire refaire, mais tu te compliques là, juste un iframe depuis le site d'openStreetMap faisait exactement la meme chose et te prenait 30 sec ;-)

2020-12-17 08:39 UTC, BenjaminDbse commented on templates/contact/contact.html.twig
> +                        <tr>
Simplement afficher le jour days en gras tout simplement

2020-12-17 08:40 UTC, BenjaminDbse commented on templates/contact/contact.html.twig
> +    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
J'peux re changer en soit mais ça m'a permit d'utiliser et de comprendre une librairie JS

2020-12-17 09:04 UTC, arnaudpilato approved these changes, later dismissed

2020-12-17 09:36 UTC, sblondeau submitted a review, later dismissed

2020-12-17 14:40 UTC, arnaudpilato approved these changes

2020-12-17 16:46 UTC, merged