S01 us04 creation formulaire contact
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #76
Opened 2020-12-23 14:57 UTC by ChenuetLoic

2020-12-30 13:53 UTC, sblondeau requested changes
la favicon doit faire 20x20 donc devrait etre BEAUCOUP plus petite (juste qq ko)

2020-12-30 13:53 UTC, sblondeau commented on src/Controller/HomeController.php
> +                ->to('loicchenuet@hotmail.fr')
pas d'adresse en dur !!!
là ça veut dire que tous les mails te sont envoyés en direct !
là on veut que les mails soient envoyés à une adresse de l'admin du site non ? donc créé une nouvelle variable d'environnement + un nouveau paramètre que tu appelle mail_admin par ex

2020-12-30 13:53 UTC, sblondeau commented on src/Entity/ContactHome.php
> +     * @Assert\Length(max="255", maxMessage="La catégorie saisie {{ value }} est trop longue,
tu n'as pas à retraduire tous les messages d'erreur en français, mais juste à activer la langue "fr" comme vu dans la quete / LC

2020-12-30 13:53 UTC, sblondeau commented on templates/home/contactHomeEmail.html.twig
> +{% block body %}
là tu n'étend rien, donc le block body ne sert à rien. Et vu que c'est un mail tu ne veux pas étendre un autre layout (ou alors tu dois faire un layoutEmail ce qui est bien si tu as d'autres type d'email à gérer plus tard).
dans tous les cas il faut que ton email est une structure html plus propre, c'est à dire déclarer doctype, html, head, body, etc.

2021-01-04 09:01 UTC, AliNedjar approved these changes, later dismissed
Tout m'a l'air ok

2021-01-04 15:57 UTC, sblondeau requested changes

2021-01-04 15:57 UTC, sblondeau commented on src/Controller/HomeController.php
> +                ->to($this->getParameter('mailer-to'))
tu vas dire que je chipotte, mais soit cohérent dans tes nommages
tu à mailer_from avec un underscore et un mailer-to avec un tiret... (préfère l'underscore avec mailer_to)

2021-01-04 16:06 UTC, ChenuetLoic commented on src/Controller/HomeController.php
> +                ->to($this->getParameter('mailer-to'))
A vrai dire je n'avais vraiment pas vue

2021-01-05 08:27 UTC, AliNedjar approved these changes
tout est ok

2021-01-05 08:43 UTC, sblondeau approved these changes

2021-01-05 08:43 UTC, merged