Fix link
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #78
Opened 2021-01-04 11:30 UTC by ChenuetLoic

2021-01-05 08:00 UTC, arnaudpilato submitted a review, later dismissed

2021-01-05 08:44 UTC, sblondeau requested changes

2021-01-05 08:44 UTC, sblondeau commented on .github/workflows/main.yml
> +<<<<<<< HEAD
conflit mal résolu!
ça ça vaut 2 gateaux! un de ta part et un du code reviewer !

2021-01-05 15:27 UTC, AliNedjar approved these changes
liens bien modifiés

2021-01-06 08:16 UTC, sblondeau approved these changes

2021-01-06 08:19 UTC, sblondeau approved these changes

2021-01-06 08:19 UTC, merged