S04 us41 admin edit home
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #80
Opened 2021-01-04 13:16 UTC by ChenuetLoic

2021-01-05 08:01 UTC, arnaudpilato approved these changes, later dismissed

2021-01-05 14:51 UTC, sblondeau requested changes

2021-01-05 14:51 UTC, sblondeau commented on templates/home/index.html.twig
> +                    <input class="btn btn-secondary btn-lg" type='submit' value='Envoyer'>
bonne pratique : utilise plutot une balise button

2021-01-06 08:16 UTC, AliNedjar approved these changes, later dismissed
tout m'a l'air ok

2021-01-06 08:24 UTC, sblondeau requested changes

2021-01-06 08:24 UTC, sblondeau commented on templates/home/index.html.twig
> +                    <button class="btn btn-secondary btn-lg" type='submit' value='Envoyer'>Envoyer</button>
c'est juste `<button class="btn btn-secondary btn-lg">Envoyer</button>`
on va y arriver :D

2021-01-06 08:49 UTC, AliNedjar approved these changes
Button changé

2021-01-06 08:49 UTC, arnaudpilato approved these changes

2021-01-06 09:30 UTC, sblondeau approved these changes

2021-01-06 09:30 UTC, merged