S04 us49 barre navigation admin
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #96
Opened 2021-01-06 13:46 UTC by ChenuetLoic

2021-01-06 13:48 UTC, Sandra-Louchart submitted a review, later dismissed

2021-01-06 13:50 UTC, AliNedjar approved these changes, later dismissed
ça m'a l'air ok

2021-01-06 19:23 UTC, sblondeau requested changes

2021-01-06 19:23 UTC, sblondeau commented on migrations/Version20210106093916.php
> +        // this up() migration is auto-generated, please modify it to your needs
là je pense qu'il y a un soucis dans ce fichier. N'aurais tu pas fais un make:migration à la place d'un d:m:m ? 
cette PR ne modifie pas la bdd donc devrait pas y avoir de Migration

2021-01-06 19:27 UTC, ChenuetLoic commented on migrations/Version20210106093916.php
> +        // this up() migration is auto-generated, please modify it to your needs
En faite pour pouvoir accéder à toute les pages suite à un pull dev de la partie de Ali j'ai du faire une make migration sinon je ne pouvais rien faire du tout c'est pour cela qu'il y a sa

2021-01-07 08:16 UTC, Sandra-Louchart approved these changes

2021-01-07 08:16 UTC, AliNedjar approved these changes
c'est tout bon

2021-01-07 08:53 UTC, sblondeau approved these changes

2021-01-07 08:53 UTC, merged