S04 us12 session
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #98
Opened 2021-01-06 15:50 UTC by AliNedjar

2021-01-06 16:37 UTC, BenjaminDbse approved these changes, later dismissed

2021-01-06 19:27 UTC, sblondeau requested changes

2021-01-06 19:27 UTC, sblondeau commented on migrations/Version20210106084239.php
> +        $this->addSql('DROP TABLE fitness');
pas normal que tu drop la table fitness 
tu n'as pas du bien faire le d:m:m avant de faire ton make:migration

2021-01-06 19:27 UTC, sblondeau commented on templates/security/login.html.twig
> +{% block title %}Log in!{% endblock %}
traduit le title

2021-01-06 19:27 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +        $contributor->setRoles(['ROLE_CONTRIBUTOR']);
c'est quoi ce role ? tu as pas juste le coach (ROLE_ADMIN) et les membres (ROLE_USER) ?

2021-01-07 09:25 UTC, ChenuetLoic submitted a review, later dismissed

2021-01-07 12:51 UTC, sblondeau requested changes

2021-01-07 12:51 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +        $contributor->setRoles(['ROLE_MEMBRE']);
ROLE_MEMBER
et $member au lieu de $contributor

2021-01-07 12:51 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +        $contributor->setRoles(['ROLE_MEMBRE']);
y a t-il une différence entre un ROLE_USER et un ROLE_MEMBER ? 
c'est envisageable s'il y a une phase de modération. Un user s'inscrit sur le site=> ROLE_USER (uniquement accès au profil) mais il faut que le coach valide le compte manuellement et il devient ROLE_MEMBER avec accès aux pages par ex à la page réservation.
A confirmer rapidement car dans ce cas il faudra créer aussi une fixture pour ROLE_USER

2021-01-07 12:51 UTC, sblondeau commented on config/packages/security.yaml
> +                # target: app_any_route
je pense qu'il manque un role_hierarchy

2021-01-12 14:29 UTC, ChenuetLoic approved these changes, later dismissed

2021-01-12 15:02 UTC, ChenuetLoic approved these changes

2021-01-12 15:45 UTC, sblondeau approved these changes

2021-01-12 15:45 UTC, merged