creation entity tarif
WildCodeSchool/orleans-php-202009-project-coachsportif pull request #99
Opened 2021-01-06 16:01 UTC by BenjaminDbse

2021-01-06 16:13 UTC, arnaudpilato approved these changes

2021-01-06 16:31 UTC, arnaudpilato submitted a review, later dismissed

2021-01-06 19:31 UTC, sblondeau requested changes
cette PR n'est pas une US
une création d'entity est seulement une tache d'US
ton US te dis que tu veux une page pour créer des tarifs
donc il te manque la partie "create" d'un CRUD (un form, traitement du form, insertion en bdd...)

2021-01-06 19:31 UTC, sblondeau commented on src/Entity/Tariff.php
> +     * @Assert\NotBlank
tu devrais ajoute un @Assert\Positive pour t'assurer que la valeur est bien un nombre > 0
https://symfony.com/doc/current/reference/constraints/Positive.html

2021-01-07 08:42 UTC, sblondeau approved these changes

2021-01-07 08:43 UTC, merged